### ISSUE TITLE
Autosave session in cookies

### ISSUE THREAD

**Issue by avently** [divyangbw/ngBaasbox#5]
Hey. Awesome library. I think would be cool if you will make autosave of session in cookies. Like Baasbox JS SDK did here https://github.com/baasbox/JS-SDK/blob/master/baasbox.js

When user logging in or signing up you can save session and when user logging out you can remove session. That's it:)

Also would be nice to see method like this:
getSingleUser(username, query) 
Because "query" field allows to specify what fields I want to get, e.g. "fields: 'visibleByAnonymouseUsers.fullname as fullname' etc. Thanks.

**Comment by divyang-joshi** [comment]
Thanks for the suggestions. The query is already implemented, just not pushed to git :D As for sessions, I'll create a task for it :+1:
